esphome:
  name: brookeledmatrix
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "***********"
  password: "***********"

  manual_ip:
    static_ip: 192.168.0.110
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "************"
    password: "*******"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

globals:
   - id: message_content
     type: std::string
     restore_value: no
     initial_value: ' "J" '
   - id: message_received
     type: int
     restore_value: no
     initial_value: '0'

time:
  - platform: sntp
    id: homeassistant_time

spi:
  clk_pin: D3
  mosi_pin: D7


display:
  - platform: max7219digit
    id: main_display
    cs_pin: D2
    num_chips: 2
    intensity: 15
    rotate_chip: 90
    scroll_mode: CONTINUOUS
    update_interval: 5s

    lambda: |-
      if(id(message_received) == 1) {
        it.print(0, 0, id(digit_font), id(message_content).c_str());
      } else {
        it.strftime(0, 0, id(digit_font), "%I:%M:%S %p", id(homeassistant_time).now());
      }




font:
  - file: "pixelmix.ttf"
    id: digit_font
    size: 6

mqtt:
  id: mqtt_client
  broker: 192.168.0.162
  port: 1883
  username: *******
  password: **********
  discovery: true
  discovery_prefix: homeassistant



  on_message:
    topic: 'brookeledmatrix'
    qos: 0

    then:

      - logger.log: msg
      - lambda: |-
                id(message_content) = x;
                id(message_received) = 1;
